import Foundation
import SwiftData
import SwiftUI

class TaskViewModel: ObservableObject {
    @Published var tasks: [TodoTask] = []
    @Published var newTaskText: String = ""
    @Published var newTaskDeadline: Date = Date()
    @Published var showDatePicker: Bool = false

    var modelContext: ModelContext? {
        didSet { fetchTasks() }
    }

    // MARK: Derived

    init() {
        // Automatically refresh when the day changes or app wakes up
        NotificationCenter.default.addObserver(forName: .NSCalendarDayChanged, object: nil, queue: .main) { [weak self] _ in
            self?.fetchTasks()
        }
        NotificationCenter.default.addObserver(forName: NSApplication.didBecomeActiveNotification, object: nil, queue: .main) { [weak self] _ in
            self?.fetchTasks()
        }
    }
    
    private func addGoalTask(title: String) {
        guard let ctx = modelContext else { return }
        let task = TodoTask(title: "🎯 \(title)")
        ctx.insert(task)
        try? ctx.save()
        fetchTasks()
    }

    var completedTodayCount: Int { tasks.filter(\.isCompleted).count }
    var pendingCount: Int        { tasks.filter { !$0.isCompleted }.count }

    // MARK: Fetch

    func fetchTasks() {
        guard let ctx = modelContext else { return }
        
        syncAutoTasks(ctx: ctx)
        
        let startOfDay = Calendar.current.startOfDay(for: Date())
        let descriptor = FetchDescriptor<TodoTask>(
            predicate: #Predicate { $0.createdAt >= startOfDay },
            sortBy: [SortDescriptor(\.createdAt)]
        )
        tasks = (try? ctx.fetch(descriptor)) ?? []
    }
    
    private func syncAutoTasks(ctx: ModelContext) {
        let startOfDay = Calendar.current.startOfDay(for: Date())
        let todayTasksDescriptor = FetchDescriptor<TodoTask>(
            predicate: #Predicate { $0.createdAt >= startOfDay }
        )
        let todayTasks = (try? ctx.fetch(todayTasksDescriptor)) ?? []
        
        let goalsDescriptor = FetchDescriptor<LongTermGoal>()
        let goals = (try? ctx.fetch(goalsDescriptor)) ?? []
        
        for goal in goals {
            // For each Daily Habit
            for habit in goal.dailyHabits {
                if !todayTasks.contains(where: { $0.linkedGoalId == habit.id }) {
                    let task = TodoTask(title: habit.title, linkedGoalId: habit.id, isAutoGenerated: true)
                    ctx.insert(task)
                }
            }
            // For each Milestone
            let now = Date()
            for milestone in goal.milestones {
                if now >= milestone.startDate && now <= milestone.endDate && milestone.quizScore == nil {
                    if !todayTasks.contains(where: { $0.linkedGoalId == milestone.id }) {
                        let task = TodoTask(title: milestone.title, linkedGoalId: milestone.id, isAutoGenerated: true)
                        ctx.insert(task)
                    }
                }
            }
        }
        try? ctx.save()
    }

    // MARK: CRUD

    func addTask() {
        let trimmed = newTaskText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, let ctx = modelContext else { return }
        let task = TodoTask(title: trimmed, deadline: showDatePicker ? newTaskDeadline : nil)
        ctx.insert(task)
        try? ctx.save()
        newTaskText = ""
        fetchTasks()
    }
    
    func addLinkedTask(title: String, goalId: UUID, deadline: Date? = nil) {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, let ctx = modelContext else { return }
        let task = TodoTask(title: trimmed, linkedGoalId: goalId, deadline: deadline)
        ctx.insert(task)
        try? ctx.save()
        fetchTasks()
    }

    func toggleTask(_ task: TodoTask) {
        if task.isCompleted { return }
        task.isCompleted = true
        task.completedAt = Date()
        
        // If it's linked to a habit or milestone, increase daysCompleted
        if let linkedId = task.linkedGoalId, task.isAutoGenerated, let ctx = modelContext {
            // We need to fetch the habit or milestone and increment
            let habitDescriptor = FetchDescriptor<DailyHabit>(predicate: #Predicate { $0.id == linkedId })
            if let habit = (try? ctx.fetch(habitDescriptor))?.first {
                habit.daysCompleted += 1
            }
            
            let milestoneDescriptor = FetchDescriptor<Milestone>(predicate: #Predicate { $0.id == linkedId })
            if let milestone = (try? ctx.fetch(milestoneDescriptor))?.first {
                milestone.daysCompleted += 1
            }
        }
        
        NotificationCenter.default.post(name: .taskCompleted, object: nil)
        try? modelContext?.save()
        fetchTasks()
    }

    func deleteTask(_ task: TodoTask) {
        modelContext?.delete(task)
        try? modelContext?.save()
        fetchTasks()
    }
}
