import Foundation
import SwiftData

@Model
final class TodoTask {
    var id: UUID
    var title: String
    var isCompleted: Bool
    var createdAt: Date
    var completedAt: Date?
    var linkedGoalId: UUID?
    var deadline: Date?
    var isAutoGenerated: Bool

    init(title: String, linkedGoalId: UUID? = nil, deadline: Date? = nil, isAutoGenerated: Bool = false) {
        self.id = UUID()
        self.title = title
        self.isCompleted = false
        self.createdAt = Date()
        self.completedAt = nil
        self.linkedGoalId = linkedGoalId
        self.deadline = deadline
        self.isAutoGenerated = isAutoGenerated
    }
}
